config/routes.rb
RbenvCapistranoDeploy::Application.routes.draw do
  resources :people

  root :to => 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :date_of_birth, :first_name, :job_title, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="row">
	  <div class="twelve columns">
	    <nav class="top-bar">
	      <ul>
	        <!-- Title Area -->
	        <li class="name">
	          <h1>
	            <%= link_to("Contacts", people_path) %>
	          </h1>
	        </li>
	        <li class="toggle-topbar"><a href="#"></a></li>
	      </ul>

	      <section>
	        <!-- Left Nav Section -->
	        <ul class="left">
	          <li class="divider"></li>
	          <li class="has-dropdown">
	            <a class="active" href="#">Item 1</a>
	            <ul class="dropdown">
	              <li><label>Section Name</label></li>
	              <li class="has-dropdown">
	                <a href="#" class="">Level 1, Has Dropdown</a>
	                <ul class="dropdown">
	                  <li><a href="#">Level 2</a></li>
	                  <li><a href="#">Level 2</a></li>
	                  <li class="has-dropdown"><a href="#">Level 2, Has Dropdown</a>
	                    <ul class="dropdown">
	                      <li><label>Section</label></li>
	                      <li><a href="#">Level 3</a></li>
	                      <li><a href="#">Level 3</a></li>
	                      <li class="divider"></li>
	                      <li><a href="#">Level 3</a></li>
	                    </ul>
	                  </li>
	                  <li><a href="#">Level 2</a></li>
	                  <li><a href="#">Level 2</a></li>
	                </ul>
	              </li>
	              <li><a href="#">Level 1</a></li>
	              <li><a href="#">Level 1</a></li>
	              <li class="divider"></li>
	              <li><label>Section Name</label></li>
	              <li><a href="#">Level 1</a></li>
	              <li><a href="#">Level 1</a></li>
	              <li><a href="#">Level 1</a></li>
	              <li class="divider"></li>
	              <li><a href="#">See all &rarr;</a></li>
	            </ul>
	          </li>
	          <li class="divider hide-for-small"></li>
	        </ul>

	        <!-- Right Nav Section -->
	        <ul class="right">
	          <li class="divider show-for-medium-and-up"></li>
	          <li class="has-dropdown">
	            <a href="#">Item 2</a>
	            <ul class="dropdown">
	              <li><label>Section Name</label></li>
	              <li><a href="#" class="">Level 1</a></li>
	              <li><a href="#">Dropdown Option</a></li>
	              <li><a href="#">Dropdown Option</a></li>
	              <li class="divider"></li>
	              <li><label>Section Name</label></li>
	              <li><a href="#">Dropdown Option</a></li>
	              <li><a href="#">Dropdown Option</a></li>
	              <li><a href="#">Dropdown Option</a></li>
	              <li class="divider"></li>
	              <li><a href="#">See all &rarr;</a></li>
	            </ul>
	          </li>
	        </ul>
	      </section>
	    </nav>
	  </div>
	</div>	
	<div class="row">
	  <div class="twelve columns">
		  <%= yield %>
	  </div>
	</div>	
</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :job_title %><br />
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Job title</th>
    <th>Date of birth</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.first_name %></td>
    <td><%= person.last_name %></td>
    <td><%= person.job_title %></td>
    <td><%= person.date_of_birth %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @person.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @person.last_name %>
</p>

<p>
  <b>Job title:</b>
  <%= @person.job_title %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @person.date_of_birth %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>